import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBarDesktop from "./components/SideBarDesktop/SideBarDesktop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutDesktop({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="Layout flex items-center justify-center h-screen">
          <div className="flex h-[600px] w-[855px] rounded-3xl bg-white p-[16px]">
            <SideBarDesktop />
             <div className="ml-[70px]">
               <main> {children}</main>  
             </div>
          </div>
        </div>  
      </body>
    </html>
  );
}
