import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBarMobile from "./components/TopBarMobile/TopBarMobile";
import FooterMobile from "./components/FooterMobile/FooterMobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutMobile({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="Layout flex flex-col items-center bg-blue-50 justify-center h-screen relative">
          <TopBarMobile/>
              <main>{children}</main>  
          <FooterMobile/>
        </div>  
      </body>
    </html>
  );
}
